version: '3.8' 

services:
  app:
    build: . # Path to the directory with your app's Dockerfile
    ports:
      - "8007:8000" # Expose FastAPI's port
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres_db:5432/purchase
    volumes:
      - files:/app/files
      - bot_files:/app/Bots/Purchasebot


volumes:
  files:
  bot_files: