"""Edit table columns

Revision ID: ac27d8a247c0
Revises: 
Create Date: 2024-05-16 10:03:10.648448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac27d8a247c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expanditure', sa.Column('deny_reason', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('deny_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'deny_reason')
    op.drop_column('expanditure', 'deny_reason')
    # ### end Alembic commands ###
